### ISSUE TITLE
Scrolling track title quite annoying...

### ISSUE THREAD

**Issue by emisjerry** [andrewmcgivery/obsidian-soundscapes#20]
Hi,

Thanks your plugin. But the flying title on the status bar quit annoying. 

Could be an option to fixed it to not flying mode?

**Comment by emisjerry** [comment]
Solved as CSS snippet:

```css
.soundscapesroot .soundscapesroot-nowplaying .soundscapesroot-nowplaying-text {
    display: inline-block;
    animation: none;  /* marquee 10s linear infinite; */
}
```
