### ISSUE TITLE
Option to hide the volume mixer from the status bar or disable it entirely

### ISSUE THREAD

**Issue by RomanMunar** [andrewmcgivery/obsidian-soundscapes#53]

**Comment by RomanMunar** [comment]
I am using this snippet for now

```scss
// hide soundscapes volume mixer.scss
.soundscapesroot-volumeIcons {
  & + input[type="range"] {
    display: none !important;
  }
  display: none !important;
}
```
